-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activities (
  id text NOT NULL,
  user_id uuid NOT NULL,
  name text,
  sport_type text,
  start_date timestamp with time zone,
  start_date_local timestamp with time zone,
  description text,
  distance double precision,
  moving_time integer,
  elapsed_time integer,
  average_speed double precision,
  max_speed double precision,
  average_pace double precision,
  average_heartrate double precision,
  max_heartrate double precision,
  training_load double precision,
  intensity double precision,
  tss double precision,
  average_watts double precision,
  max_watts double precision,
  weighted_average_watts double precision,
  average_cadence double precision,
  max_cadence double precision,
  gap double precision,
  average_stride_length double precision,
  efficiency_factor double precision,
  average_stroke_rate double precision,
  swim_stroke_count integer,
  swolf double precision,
  pool_length double precision,
  total_elevation_gain double precision,
  total_elevation_loss double precision,
  max_elevation double precision,
  aerobic_te double precision,
  anaerobic_te double precision,
  kilojoules double precision,
  calories double precision,
  interval_count integer,
  source text,
  raw_data jsonb,
  synced_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activities_pkey PRIMARY KEY (id, user_id),
  CONSTRAINT activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.events (
  id text NOT NULL,
  user_id uuid NOT NULL,
  title text,
  category text,
  type text,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  description text,
  distance double precision,
  moving_time integer,
  raw_data jsonb,
  synced_at timestamp with time zone DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id, user_id),
  CONSTRAINT events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.fitness_metrics (
  date date NOT NULL,
  user_id uuid NOT NULL,
  ctl double precision,
  atl double precision,
  tsb double precision,
  ramprate double precision,
  synced_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fitness_metrics_pkey PRIMARY KEY (date, user_id),
  CONSTRAINT fitness_metrics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.sync_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  sync_type text NOT NULL,
  status text NOT NULL,
  records_fetched integer DEFAULT 0,
  records_saved integer DEFAULT 0,
  error_message text,
  started_at timestamp with time zone DEFAULT now(),
  finished_at timestamp with time zone,
  CONSTRAINT sync_log_pkey PRIMARY KEY (id),
  CONSTRAINT sync_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.training_zones (
  user_id uuid NOT NULL,
  sport_type text NOT NULL,
  zone_type text NOT NULL,
  zone_1_min double precision,
  zone_1_max double precision,
  zone_2_min double precision,
  zone_2_max double precision,
  zone_3_min double precision,
  zone_3_max double precision,
  zone_4_min double precision,
  zone_4_max double precision,
  zone_5_min double precision,
  zone_5_max double precision,
  zone_6_min double precision,
  zone_6_max double precision,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT training_zones_pkey PRIMARY KEY (user_id, sport_type, zone_type),
  CONSTRAINT training_zones_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  intervals_athlete_id text,
  intervals_api_key text,
  updated_at timestamp with time zone DEFAULT now(),
  calendar_ics_url text,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.wellness (
  date date NOT NULL,
  user_id uuid NOT NULL,
  sleep_secs integer,
  sleep_quality integer,
  sleep_score double precision,
  resting_hr double precision,
  average_resting_hr double precision,
  hrv double precision,
  hrv_score double precision,
  hrv4training_score integer,
  feel integer,
  mood integer,
  motivation integer,
  weight double precision,
  body_fat double precision,
  ctl double precision,
  atl double precision,
  tsb double precision,
  readiness double precision,
  soreness integer,
  fatigue integer,
  stress integer,
  systolic_bp double precision,
  diastolic_bp double precision,
  spo2 double precision,
  notes text,
  raw_data jsonb,
  synced_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wellness_pkey PRIMARY KEY (date, user_id),
  CONSTRAINT wellness_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);